import type { AccountRole } from "@/lib/auth/roles";
import type { InteractiveMessagePayload } from "@/lib/whatsapp/interactive";

export type {
  InteractiveMessagePayload,
  InteractiveButtonsPayload,
  InteractiveListPayload,
  InteractiveButton,
  InteractiveListRow,
  InteractiveListSection,
} from "@/lib/whatsapp/interactive";

export interface Profile {
  id: string;
  user_id: string;
  full_name: string;
  email: string;
  avatar_url?: string;
  /**
   * Legacy free-form role column from migration 001. Never read
   * by the app since 017_account_sharing.sql introduced the typed
   * `account_role` enum. Flagged for removal in a later cleanup
   * migration — kept on the type so existing destructures don't
   * break.
   */
  role: string;
  /**
   * Opted-in beta feature keys for this account. The column survives
   * for future beta gates; no current feature reads it (Flows was
   * the last user and went to soft-GA in PR #134). Defaults to `[]`
   * for every profile; toggled per-account via a direct UPDATE on
   * the `profiles` row.
   */
  beta_features?: string[];
  /**
   * Account this profile is a member of. Added by
   * `017_account_sharing.sql`; NOT NULL in the DB post-backfill.
   * Optional on the type only because older serialised payloads
   * (cached client state, test fixtures) may not have it yet.
   */
  account_id?: string;
  /**
   * Caller's role within their account. Source of truth for every
   * role-gated UI / API check — call `hasMinRole` from
   * `@/lib/auth/roles` rather than comparing this string directly.
   */
  account_role?: AccountRole;
  created_at: string;
}

// ============================================================
// Account-sharing entities (017_account_sharing.sql)
// ============================================================

export interface Account {
  id: string;
  name: string;
  /** auth.users.id of the immutable owner. */
  owner_user_id: string;
  created_at: string;
  updated_at: string;
}

/**
 * Hydrated member row for the Settings → Members tab. Combines
 * the profile and its account_role for a single member of the
 * caller's account. Sensitive fields (email) are populated only
 * when the caller has admin+ — agents and viewers see name +
 * avatar + role only.
 */
export interface AccountMember {
  user_id: string;
  full_name: string;
  email: string | null;
  avatar_url: string | null;
  role: AccountRole;
  joined_at: string;
}

/**
 * Outstanding invite link row. `token_hash` is intentionally
 * absent — it lives only in the DB and on the server. The
 * plaintext token is returned once at creation time and surfaced
 * via the invite URL; never re-emitted.
 */
export interface AccountInvitation {
  id: string;
  account_id: string;
  /** Roles offered via invite — owner is never offered. */
  role: Exclude<AccountRole, "owner">;
  created_by_user_id: string | null;
  label: string | null;
  created_at: string;
  expires_at: string;
  accepted_at: string | null;
  accepted_by_user_id: string | null;
}

export interface Contact {
  id: string;
  user_id: string;
  account_id: string;
  /** Empty string for a contact Meta only ever identified by BSUID —
   *  see `wa_user_id`. */
  phone: string;
  /** Digits-only form of `phone`, generated by the DB (migration 022)
   *  and unique per account. Read-only. */
  phone_normalized?: string;
  /** WhatsApp business-scoped user ID (migration 040). Unique per
   *  account, and the only identity Meta sends for a customer who has
   *  adopted a WhatsApp username. */
  wa_user_id?: string | null;
  /** Portfolio-level BSUID. Reference only — never a lookup key. */
  wa_parent_user_id?: string | null;
  /** WhatsApp username without the leading @. Display only: usernames
   *  are user-changeable, so they must never key a contact. */
  wa_username?: string | null;
  /** Supabase anonymous-auth `auth.uid()` for a contact who arrived via
   *  the web-chat widget (migration 046). Unique per account when set;
   *  never present alongside a real `phone`. */
  widget_visitor_id?: string | null;
  /** Facebook Messenger page-scoped user ID (migration 055). Unique per
   *  account, asserted server-side by Meta's webhook — same trust model
   *  as `wa_user_id`, not a self-asserted identity. */
  messenger_psid?: string | null;
  /** Instagram-scoped user ID (migration 055). Same shape as
   *  `messenger_psid`, keyed to the account's connected IG business
   *  account instead of a Page. */
  instagram_igsid?: string | null;
  /** Informational only (migration 054) — passed through from a
   *  verified in-app/WebView widget handoff. Never used for contact
   *  matching; phone stays the sole identity key. */
  wallet_id?: string | null;
  name?: string;
  /** Not new — this pre-existing CRM field also doubles as the Email
   *  channel's identity key (migration 056): inbound mail is matched
   *  case-insensitively against it. See migration 056's header for why
   *  there's no dedicated `email_*_id` column and no uniqueness
   *  constraint here, unlike `messenger_psid`/`instagram_igsid`. */
  email?: string;
  company?: string;
  /** ISO 3166-1 alpha-2, upper-case (migration 069). */
  country?: string | null;
  /** Preferred conversation language, ISO 639 lower-case, optionally with
   *  a region (migration 069). AI drafts and auto-replies answer in it. */
  language?: string | null;
  /** Who set `language`: an agent, or AI detection (migration 069). */
  language_source?: 'manual' | 'detected' | null;
  avatar_url?: string;
  /** Lifecycle report follow-up (migration 052). Defaults to 'lead' for
   *  every contact — set manually from the contact form, or via the
   *  `set_lifecycle_stage` automation step. */
  lifecycle_stage?: LifecycleStage;
  /** Stamped on every `lifecycle_stage` write — see `LifecycleReport`'s
   *  `movedIn` in @/lib/reports/queries for how this is used (and its
   *  documented "latest transition only" limitation). */
  lifecycle_stage_changed_at?: string | null;
  created_at: string;
  updated_at: string;
  /** Hydrated by queries that embed `contact_tags(tags(*))` (e.g. the
   *  Inbox conversation list, for tag filtering). Absent otherwise. */
  tags?: Tag[];
}

export type LifecycleStage = 'lead' | 'active' | 'customer' | 'churned';

export interface Tag {
  id: string;
  /** Creator (auth user id). */
  user_id: string;
  name: string;
  color: string;
  created_at: string;
  /** Migration 068. Optional so hand-built fixtures still type-check. */
  description?: string | null;
  /** Offered when tagging a contact (migration 068; undefined = true). */
  for_contacts?: boolean;
  /** Offered when labelling a conversation (migration 068; undefined = true). */
  for_conversations?: boolean;
  updated_at?: string;
  /**
   * Propose and approve (migration 084). Undefined = approved. A tag that is
   * not approved is only ever seen by its proposer and by reviewers, and is
   * never applied. A proposed replacement for the live values is NOT on the
   * row (migration 088 moved it to `approval_pending_edits`, readable by the
   * proposer and reviewers only); `edit_status` says one exists.
   * `pending_edit` is never populated any more.
   */
  approval_status?: 'approved' | 'pending' | 'rejected';
  proposed_by?: string | null;
  proposed_at?: string | null;
  decided_by?: string | null;
  decided_at?: string | null;
  decision_note?: string | null;
  pending_edit?: Record<string, unknown> | null;
  edit_status?: 'pending' | 'rejected' | null;
}

export interface ContactTag {
  id: string;
  contact_id: string;
  tag_id: string;
}

export interface CustomField {
  id: string;
  user_id: string;
  /** Tenancy key — NOT NULL since migration 017. */
  account_id: string;
  field_name: string;
  field_type: string;
  field_options?: Record<string, unknown>;
  created_at: string;
}

export interface ContactCustomValue {
  id: string;
  contact_id: string;
  custom_field_id: string;
  value?: string;
}

export interface ContactNote {
  id: string;
  contact_id: string;
  /** Author — fixed at creation (migration 072 blocks changing it). */
  user_id: string;
  note_text: string;
  created_at: string;
  /** Stamped by the database when the text is edited (migration 072). */
  edited_at?: string | null;
  edited_by?: string | null;
}

export type ConversationStatus = 'open' | 'pending' | 'closed';

/** Migration 047. Sorts/badges in the inbox; set manually from the
 *  thread header or via the `set_priority` automation step (e.g. a
 *  condition on a "VIP" custom field → set_priority: urgent). */
export type ConversationPriority = 'urgent' | 'high' | 'normal' | 'low';

/** Which channel a given message came in/went out on. Introduced in
 *  migration 046 as a whole-conversation property, then moved down to
 *  the message level in migration 048 once a single conversation could
 *  span both channels (WhatsApp + Web Widget merged by contact).
 *  Messenger and Instagram added in migration 055; Email (Microsoft 365
 *  / Outlook, via Microsoft Graph) added in migration 056; Gmail added
 *  in migration 058 — kept distinct from `'email'` even though both are
 *  "email", since an account may connect one, the other, or both (e.g.
 *  support@ on Gmail and sales@ on Microsoft 365), same reasoning
 *  Messenger/Instagram stay distinct despite both being Meta.
 *  WhatsApp-only send affordances (templates, interactive buttons/lists)
 *  only make sense for `'whatsapp'` — see send-message.ts and the
 *  automation engine's per-step channel guards. */
export type ChannelType = 'whatsapp' | 'web_widget' | 'messenger' | 'instagram' | 'email' | 'gmail';

export interface Conversation {
  id: string;
  user_id: string;
  contact_id: string;
  status: ConversationStatus;
  /** Rollup of the most recent message's channel (migration 048) — a
   *  merged conversation can contain messages from both channels, so
   *  this (not a fixed per-conversation channel) is what UI badges show
   *  and what an agent's reply defaults to sending on. */
  last_channel_type: ChannelType;
  priority: ConversationPriority;
  assigned_agent_id?: string;
  /** Team a conversation is routed to (migration 043); orthogonal to
   *  `assigned_agent_id` — a team assignment always resolves to a
   *  specific agent, but the team pointer is kept so the inbox can
   *  bucket/filter by team. */
  assigned_team_id?: string | null;
  /** Conversation-level topic labels (migration 044) — reuses the same
   *  `tags` palette as contact tags, joined via `conversation_labels`.
   *  Independent of `contact.tags`: labelling "billing issue" on this
   *  conversation doesn't tag the contact, since the same contact may
   *  have unrelated conversations later. */
  labels?: Tag[];
  last_message_text?: string;
  last_message_at?: string;
  /** True from the moment a customer message arrives until the next
   *  reply on either channel (migration 049) — drives the Inbox's
   *  "aging response" indicator. */
  awaiting_response: boolean;
  /** When the customer's most recent message arrived — independent of
   *  `last_message_at`, which reflects ANY message including our own
   *  replies. Null for a conversation with no customer message yet. */
  last_customer_message_at?: string | null;
  /** When this conversation was most recently closed (migration 050) —
   *  null while open/pending, cleared on reopen. Powers the Resolutions
   *  report's open→closed duration; rows closed before this migration
   *  are backfilled from `updated_at` as an approximation. */
  closed_at?: string | null;
  unread_count: number;
  created_at: string;
  updated_at: string;
  contact?: Contact;
  /**
   * AI auto-reply state for this thread (migration 029 + 033):
   *  - `ai_autoreply_disabled` — the bot is paused here (a human took
   *    over, or the model handed off). Sticky until re-enabled.
   *  - `ai_reply_count` — how many times the bot has auto-replied,
   *    checked against the account's per-conversation cap.
   *  - `ai_handoff_summary` — short internal note the bot wrote when it
   *    handed off, shown to whoever takes the thread over.
   */
  ai_autoreply_disabled?: boolean;
  ai_reply_count?: number;
  ai_handoff_summary?: string | null;
}

// ============================================================
// Conversation session log (migration 065)
//
// klink.cloud parity — a "session log" / "case log" per conversation:
// assigned/reassigned/priority changes are logged automatically by a DB
// trigger; closed/reopened go through close_conversation_with_note /
// reopen_conversation RPCs, so a closure note is enforced server-side.
// ============================================================

export type ConversationEventType =
  | 'assigned'
  | 'unassigned'
  | 'team_assigned'
  | 'team_unassigned'
  | 'priority_changed'
  | 'closed'
  | 'reopened';

export interface ConversationEvent {
  id: string;
  conversation_id: string;
  event_type: ConversationEventType;
  /** Null for an automation/system-driven event. */
  actor_user_id?: string | null;
  /** Required (enforced by a DB CHECK) when event_type is 'closed'. */
  note?: string | null;
  /** e.g. { agent_id } / { team_id } / { from, to } depending on event_type. */
  metadata: Record<string, string | null>;
  created_at: string;
}

// ============================================================
// Notifications (migration 027)
// ============================================================

export type NotificationType =
  | 'conversation_assigned'
  | 'mention'
  | 'ticket_assigned'
  | 'ticket_mention'
  /** Migration 081: a watched ticket changed status / assignee, or got a comment. */
  | 'ticket_updated'
  | 'ticket_comment'
  /** Migration 084: a proposal waits for a reviewer / a proposal was decided. */
  | 'approval_requested'
  | 'approval_decided'
  /** Migration 085: the Jira connection needs reconnecting / a linked Jira issue reached Done. */
  | 'jira_reauth_required'
  | 'jira_issue_done'
  /** Migration 086: a ticket's SLA target is close to its limit / was missed. */
  | 'ticket_sla_at_risk'
  | 'ticket_sla_breached'
  /** Monthly AI token budget reached 80% / 100% (migration 075). */
  | 'ai_budget'
  /** Migration 098: an @mention in a Sembang channel message. */
  | 'sembang_mention'
  /** Migration 099: assigned a Sembang task (not fired for self-assignment). */
  | 'sembang_task_assigned'
  /** Migration 100: every Sembang DM message, not just @mentions — skipped
   *  when the same message also fires a sembang_mention for that recipient. */
  | 'sembang_dm_message';

export interface Notification {
  id: string;
  account_id: string;
  /** Recipient — the agent this notification is for. */
  user_id: string;
  type: NotificationType;
  conversation_id?: string;
  contact_id?: string;
  /** Migration 063. Set on ticket_assigned / ticket_mention notifications. */
  ticket_id?: string;
  /** Migration 095. The ticket comment a ticket_mention notification is about. */
  comment_id?: string;
  /** Migration 098. Set on sembang_mention notifications. */
  sembang_channel_id?: string;
  sembang_message_id?: string;
  /** Migration 099. Set on sembang_task_assigned notifications. */
  sembang_task_id?: string;
  /** Who triggered it. Null when an automation/system assigned it. */
  actor_user_id?: string;
  title: string;
  body?: string;
  read_at?: string;
  created_at: string;
}

// ============================================================
// TICKETS (migration 063)
// ============================================================

/** `in_progress` was added in migration 081 (Open, In progress, Pending,
 *  Resolved, Closed). */
export type TicketStatus = 'open' | 'in_progress' | 'pending' | 'resolved' | 'closed';

/** Same four-value scale as ConversationPriority — one shared mental
 *  model for "how urgent" across conversations and tickets. */
export type TicketPriority = 'urgent' | 'high' | 'normal' | 'low';

export type TicketCategory =
  | 'general'
  | 'billing'
  | 'technical'
  | 'feature_request'
  | 'bug'
  | 'account'
  | 'other';

export interface Ticket {
  id: string;
  account_id: string;
  /** Human-readable, per-account sequential number (#1, #2, ...) —
   *  assigned via the next_ticket_number RPC at creation time. */
  ticket_number: number;
  contact_id: string;
  /** The chat this ticket was raised from, if any — null for tickets
   *  raised directly from a Contact profile. */
  conversation_id?: string | null;
  subject: string;
  description?: string | null;
  category: TicketCategory;
  status: TicketStatus;
  priority: TicketPriority;
  assigned_agent_id?: string | null;
  assigned_team_id?: string | null;
  created_by?: string | null;
  resolved_at?: string | null;
  closed_at?: string | null;
  /** Values for admin-defined ticket fields (migration 066), keyed by
   *  TicketFieldDefinition.id. */
  custom_fields?: TicketCustomValues;
  /** Migration 081. Date only (yyyy-mm-dd), no time of day. */
  due_date?: string | null;
  /** Migration 081. Lower-case, trimmed, at most 10 of 30 chars. */
  labels?: string[];
  /** Migration 081. Position on the board: higher is nearer the top. */
  board_rank?: number;
  /** Migration 096. How the ticket was resolved (a ticket_resolutions row).
   *  Kept when the ticket is re-opened; shown only while it is Resolved or Closed. */
  resolution_id?: string | null;
  /** Migration 096. Optional free text with the resolution, at most 2000 characters. */
  resolution_note?: string | null;
  created_at: string;
  updated_at: string;
  // Migration 086 (ticket SLA). Written only by the database; see src/lib/sla.
  sla_policy_id?: string | null;
  sla_first_response_due_at?: string | null;
  sla_first_response_risk_at?: string | null;
  sla_first_response_at?: string | null;
  sla_first_response_state?: 'none' | 'running' | 'paused' | 'met' | 'breached';
  sla_resolution_due_at?: string | null;
  sla_resolution_risk_at?: string | null;
  sla_resolution_state?: 'none' | 'running' | 'paused' | 'met' | 'breached';
  sla_paused_at?: string | null;
  sla_stopped_at?: string | null;
  sla_evaluated_at?: string | null;
  // Optional joins, populated by callers that need them.
  contact?: Contact;
  assigned_team?: Team;
}

export type TicketFieldType =
  | 'text'
  | 'textarea'
  | 'number'
  | 'date'
  | 'dropdown'
  | 'checkbox';

/** string for text/textarea/dropdown/date (ISO yyyy-mm-dd), number for
 *  number, boolean for checkbox. */
export type TicketCustomValue = string | number | boolean;
export type TicketCustomValues = Record<string, TicketCustomValue>;

/** One field on the account's customizable ticket form (migration 066). */
/** Migration 096: one entry of the account's catalogue of ticket resolutions. */
export interface TicketResolution {
  id: string;
  account_id: string;
  name: string;
  position: number;
  /** false = archived: not offered for new resolutions, still names old ones. */
  is_active: boolean;
  /** "Resolved in Jira" / "Closed automatically": used by the database, cannot be archived. */
  is_system: boolean;
  system_key: 'resolved_in_jira' | 'closed_automatically' | null;
  created_at: string;
  updated_at: string;
}

export interface TicketFieldDefinition {
  id: string;
  account_id: string;
  label: string;
  field_type: TicketFieldType;
  /** Dropdown choices; empty for other types. */
  options: string[];
  is_required: boolean;
  /** Ticket categories this field appears on; empty = all of them. */
  applies_to_categories: TicketCategory[];
  position: number;
  /** false = archived: hidden from new forms, still labels old values. */
  is_active: boolean;
  created_at: string;
  updated_at: string;
}

export interface TicketComment {
  id: string;
  ticket_id: string;
  account_id: string;
  author_id?: string | null;
  body: string;
  /** Array of mentioned user_ids — same shape as messages.mentions. Includes the
   *  members a mentioned team expanded to (migration 095). */
  mentions: string[];
  /** Migration 095: ids of the teams @mentioned in the comment (display only). */
  mention_teams?: string[];
  created_at: string;
  /** Migration 081: set by the DB when the body is edited. */
  edited_at?: string | null;
  /** Migration 085: 'jira' for a note copied from a Jira comment (no author). */
  source?: 'vircle' | 'jira';
  /** Migration 085: the Jira display name of the comment's author. */
  jira_author?: string | null;
  jira_comment_id?: string | null;
  /** Migration 085: the comment was deleted in Jira (the text is kept). */
  deleted_in_jira?: boolean;
}

/** System-logged ticket history events (migration 064) — status/priority/
 *  category/assignment changes, written by a DB trigger so every write
 *  path (UI, future automation steps) is captured for free. */
export type TicketActivityEventType =
  | 'created'
  | 'status_changed'
  | 'priority_changed'
  | 'category_changed'
  | 'assigned_agent_changed'
  | 'assigned_team_changed'
  | 'custom_field_changed'
  // Migration 081. Link events store the point of view of this ticket in
  // from_value (blocks / blocked_by / relates / duplicates / duplicated_by)
  // and the other ticket's id in to_value; description_changed has no values.
  | 'due_date_changed'
  | 'labels_changed'
  | 'summary_changed'
  | 'description_changed'
  | 'link_added'
  | 'link_removed'
  | 'attachment_added'
  // Migration 085 (Jira link): `detail` holds the issue key. jira_linked /
  // jira_unlinked: to_value = key. jira_status_synced: from / to = the ticket
  // statuses, no actor ("by Jira"). jira_status_pushed: to_value = the Jira
  // status Vircle moved the issue to.
  | 'jira_linked'
  | 'jira_unlinked'
  | 'jira_status_synced'
  | 'jira_status_pushed'
  // Migration 095 (ticket mentions). requested: to_value = the person (empty for a
  // request to a team), from_value = the team id, detail = the comment id. done:
  // to_value = the person, from_value = replied | marked_done | ticket_closed,
  // detail = the comment id (or a count for ticket_closed). cancelled: to_value =
  // the person, from_value = cancelled | comment_deleted, detail = the comment id
  // (or a count for comment_deleted).
  | 'mention_requested'
  | 'mention_done'
  | 'mention_cancelled'
  // Migration 096. resolved_as: to_value = the resolution's name, detail = the
  // note. resolution_changed: from_value / to_value = names (from empty when
  // there was none), detail = the note. No actor for the system and for Jira.
  | 'resolved_as'
  | 'resolution_changed';

export interface TicketActivity {
  id: string;
  ticket_id: string;
  account_id: string;
  actor_id?: string | null;
  /** Set for custom_field_changed — the TicketFieldDefinition edited. */
  field_id?: string | null;
  event_type: TicketActivityEventType;
  from_value?: string | null;
  to_value?: string | null;
  /** Migration 085: extra context, the Jira issue key for the jira_* events. */
  detail?: string | null;
  created_at: string;
}

/** Migration 095: a person asked (by @mention) to respond on a ticket. */
export type TicketMentionStatus = 'open' | 'done' | 'cancelled';
export type TicketMentionReason = 'replied' | 'marked_done' | 'ticket_closed' | 'cancelled';

export interface TicketMention {
  id: string;
  account_id: string;
  ticket_id: string;
  /** The comment that asked; null once that comment was deleted. */
  comment_id: string | null;
  mentioned_user_id: string;
  requested_by: string | null;
  /** Set when the request came through an @team. */
  via_team_id: string | null;
  kind: 'response' | 'fyi';
  status: TicketMentionStatus;
  created_at: string;
  resolved_at: string | null;
  resolved_by: string | null;
  resolved_reason: TicketMentionReason | null;
  nudged_at: string | null;
}

/** Migration 081: people following a ticket. Creator and assignee are added by the DB. */
export interface TicketWatcher {
  ticket_id: string;
  user_id: string;
  account_id: string;
  created_at: string;
}

export type TicketLinkType = 'blocks' | 'relates' | 'duplicates';

/** Migration 081: `from` blocks / relates to / duplicates `to`. */
export interface TicketLink {
  id: string;
  account_id: string;
  from_ticket_id: string;
  to_ticket_id: string;
  link_type: TicketLinkType;
  created_by?: string | null;
  created_at: string;
}

/** Migration 081: a file on a ticket (stored in the chat-media bucket). */
export interface TicketAttachment {
  id: string;
  ticket_id: string;
  account_id: string;
  storage_path: string;
  url: string;
  filename: string;
  mime_type: string;
  size_bytes: number;
  uploaded_by?: string | null;
  /** Migration 087: 'jira' for a file copied from a linked Jira issue. */
  source?: 'vircle' | 'jira';
  jira_attachment_id?: string | null;
  created_at: string;
}

/** Migration 081: a saved ticket filter; `filter` is the serialised TicketFilters. */
export interface TicketSavedFilter {
  id: string;
  account_id: string;
  user_id: string;
  name: string;
  filter: Record<string, unknown>;
  is_shared: boolean;
  created_at: string;
}

export type SenderType = 'customer' | 'agent' | 'bot';
export type ContentType =
  | 'text'
  | 'image'
  | 'document'
  | 'audio'
  | 'video'
  | 'location'
  | 'template'
  /** Customer tapped a reply button or list row on a message we sent. */
  | 'interactive';
export type MessageStatus = 'sending' | 'sent' | 'delivered' | 'read' | 'failed';

export interface Message {
  id: string;
  conversation_id: string;
  sender_type: SenderType;
  /** The team member who sent this — set for internal comments (always)
   *  and, since the Leaderboard/Users reports needed per-agent
   *  attribution, for ordinary outbound agent sends too. Never set for
   *  bot/system/customer messages. NULL on every agent message sent
   *  before that reporting work shipped (no historical backfill). */
  sender_id?: string;
  content_type: ContentType;
  content_text?: string;
  /** Original HTML body, for an Email(MS365)/Gmail message whose
   *  source was HTML (migration 061). Null for every other channel
   *  and for a genuinely plain-text email. Rendered client-side inside
   *  a sandboxed iframe — see EmailHtmlView — never trusted as-is. */
  content_html?: string | null;
  media_url?: string;
  /**
   * MIME type of `media_url`'s content, as Meta reported it. Inbound
   * media only — outbound URLs already carry a filename and extension.
   * Null on every row written before migration 039.
   */
  media_type?: string | null;
  template_name?: string;
  message_id?: string;
  /** Which channel this specific message came in/went out on
   *  (migration 048) — a merged conversation can interleave WhatsApp
   *  and Web Widget messages, so this is per-message, not inherited
   *  from the conversation. */
  channel_type: ChannelType;
  status: MessageStatus;
  created_at: string;
  reply_to_message_id?: string;
  /**
   * Only set when `content_type === 'interactive'` — the stable id of
   * the button or list row the customer tapped. The Flows engine uses
   * this to route the next node; the inbox bubble uses it as a styling
   * cue (renders with a "↩ button reply" affordance).
   */
  interactive_reply_id?: string;
  /**
   * Structured payload of an OUTBOUND interactive message (reply
   * buttons or list) we sent. Lets the thread re-render the buttons /
   * rows, not just the body text. Only set when `content_type ===
   * 'interactive'` and `sender_type` is agent/bot. Migration 035.
   */
  interactive_payload?: InteractiveMessagePayload;
  /**
   * True when the AI auto-reply bot generated + sent this message (as
   * opposed to a human agent or a deterministic Flow/automation send,
   * which all share `sender_type='bot'`/`'agent'`). Drives the "AI"
   * badge in the inbox. Migration 033.
   */
  ai_generated?: boolean;
  /**
   * Meta's reason for a failed send, from the `failed` status webhook's
   * `errors[0]` (code / title / error_data.details). Only set when
   * `status === 'failed'`; never cleared by a later status. Migration 042.
   */
  error_code?: number | null;
  error_title?: string | null;
  error_details?: string | null;
  /**
   * True for an internal comment — never sent to WhatsApp, visible to
   * teammates only. Migration 045. Defaults to false for every row
   * written before this migration and every ordinary customer-facing
   * message since.
   */
  is_internal?: boolean;
  /** Mentioned user_ids, only meaningful when `is_internal` is true. */
  mentions?: string[];
  /** Knowledge articles an AI reply was based on. Only set on the internal
   *  "AI answered from" note (migration 077); null / absent everywhere else. */
  kb_sources?: { id: string; title: string }[] | null;
  /** "Move to Trash" flag (migration 062) — true hides the message
   *  from its own conversation thread and surfaces it in the
   *  account-wide Pending Delete panel instead of deleting it
   *  outright. `pending_delete_at` is when it was flagged. */
  pending_delete?: boolean;
  pending_delete_at?: string | null;
}

export type ReactionActor = 'customer' | 'agent';

export interface MessageReaction {
  id: string;
  message_id: string;
  conversation_id: string;
  actor_type: ReactionActor;
  actor_id?: string;
  emoji: string;
  created_at: string;
}

export interface WhatsAppConfig {
  id: string;
  user_id: string;
  phone_number_id: string;
  waba_id?: string;
  access_token: string;
  verify_token?: string;
  status: 'connected' | 'disconnected';
  connected_at?: string;
  /**
   * Set when POST /{phone_number_id}/register last succeeded. NULL
   * means the number was saved but never actually subscribed for
   * webhooks on Meta's side — inbound events will be silently lost.
   */
  registered_at?: string;
  /** Set when POST /{waba_id}/subscribed_apps last succeeded. */
  subscribed_apps_at?: string;
  /** Last error from /register; cleared on success. */
  last_registration_error?: string;
  /**
   * When true (the default), the inbound webhook copies received media
   * into the `chat-media` bucket so attachments outlive Meta's ~30-day
   * retention. Turning it off keeps storage flat and accepts that
   * inbound attachments expire. Migration 039.
   */
  mirror_inbound_media?: boolean;
  /** Manual pause switch, independent of `status` (migration 097). */
  enabled?: boolean;
}

export interface WebWidgetConfig {
  id: string;
  account_id: string;
  /** Public, non-secret identifier embedded in the `<script>` tag's
   *  `data-widget-token` attribute — not a credential, just how a
   *  visitor's browser tells us which account/config to bootstrap. */
  widget_token: string;
  name: string;
  welcome_message: string;
  primary_color: string;
  avatar_url?: string | null;
  position: 'left' | 'right';
  /** Origins allowed to embed this widget (CORS allow-list). Empty
   *  array means unrestricted — any origin may embed. */
  allowed_origins: string[];
  enabled: boolean;
  /** How a web visitor's claimed identity gets confirmed (migration 092).
   *  Only 'none' is implemented; the others are stored but "coming soon". */
  verification_mode?: 'none' | 'email_code' | 'whatsapp_code';
  /** Last four characters of the in-app identity secret, or null when none
   *  has been generated. The secret itself is never sent to the client. */
  identity_secret_last4?: string | null;
  identity_secret_rotated_at?: string | null;
  created_at: string;
  updated_at: string;
}

/** Connection status shared by Messenger/Instagram config rows — GET
 *  responses for both never include the token, only this summary. */
export interface MetaChannelConnectionStatus {
  connected: boolean;
  page_name?: string | null;
  connected_at?: string | null;
  needs_reauth: boolean;
  status: 'connected' | 'disconnected' | 'error';
  /** Set once the Page is subscribed to comment events (migration 074). */
  comments_enabled_at?: string | null;
  /** Manual pause switch, independent of `status` (migration 097). Absent
   *  (not just `false`) when there's no config row to read it from. */
  enabled?: boolean;
}

export type MessengerConnectionStatus = MetaChannelConnectionStatus;

export interface InstagramConnectionStatus extends MetaChannelConnectionStatus {
  ig_username?: string | null;
}

/** Email (Microsoft 365) channel connection status — migration 056.
 *  Not a `MetaChannelConnectionStatus` extension: it's a Microsoft
 *  Graph connection, not a Meta one, and shows a mailbox address
 *  rather than a Page/IG name. */
export interface EmailConnectionStatus {
  connected: boolean;
  mailbox_address?: string | null;
  connected_at?: string | null;
  needs_reauth: boolean;
  status: 'connected' | 'disconnected' | 'error';
  /** Manual pause switch, independent of `status` (migration 097). */
  enabled?: boolean;
}

/** Gmail channel connection status — migration 058. Unlike every other
 *  channel's status shape, this carries the Pub/Sub push-endpoint URL
 *  (with its verify token) an admin needs to paste into Google Cloud
 *  Console, and whether that one-time setup has actually been done
 *  (`pubsub_configured`) — Gmail's inbound delivery doesn't self-
 *  register the way Microsoft 365's or Messenger/Instagram's do. */
export interface GmailConnectionStatus {
  connected: boolean;
  email_address?: string | null;
  connected_at?: string | null;
  needs_reauth: boolean;
  status: 'connected' | 'disconnected' | 'error';
  pubsub_configured: boolean;
  push_endpoint_url: string | null;
  /** Manual pause switch, independent of `status` (migration 097). */
  enabled?: boolean;
}

// Raw Meta status enum. We persist this verbatim from Meta (sync + webhook)
// rather than collapsing to a local TitleCase set — distinctions like
// PAUSED vs DISABLED vs IN_APPEAL drive the edit/resubmit/delete flows.
// DRAFT is the local-only state before the row is submitted to Meta.
export type MessageTemplateStatus =
  | 'DRAFT'
  | 'PENDING'
  | 'APPROVED'
  | 'REJECTED'
  | 'PAUSED'
  | 'DISABLED'
  | 'IN_APPEAL'
  | 'PENDING_DELETION';

export type TemplateButton =
  | { type: 'QUICK_REPLY'; text: string }
  | { type: 'URL'; text: string; url: string; example?: string }
  | { type: 'PHONE_NUMBER'; text: string; phone_number: string }
  | { type: 'COPY_CODE'; text: string; example: string };

export interface TemplateSampleValues {
  body?: string[];
  header?: string[];
}

export interface MessageTemplate {
  id: string;
  user_id: string;
  name: string;
  category: 'Marketing' | 'Utility' | 'Authentication';
  language?: string;
  header_type?: 'text' | 'image' | 'video' | 'document';
  header_content?: string;
  header_handle?: string;
  header_media_url?: string;
  body_text: string;
  footer_text?: string;
  buttons?: TemplateButton[];
  sample_values?: TemplateSampleValues;
  status?: MessageTemplateStatus;
  meta_template_id?: string;
  rejection_reason?: string;
  quality_score?: 'GREEN' | 'YELLOW' | 'RED';
  submission_error?: string;
  last_submitted_at?: string;
  created_at: string;
}

export interface Pipeline {
  id: string;
  user_id: string;
  name: string;
  created_at: string;
}

export interface PipelineStage {
  id: string;
  pipeline_id: string;
  name: string;
  position: number;
  color: string;
  created_at: string;
}

export type DealStatus = 'open' | 'won' | 'lost';

export interface Deal {
  id: string;
  user_id: string;
  pipeline_id: string;
  stage_id: string;
  /**
   * Nullable after migration 004 — becomes NULL when the referenced
   * contact is deleted (ON DELETE SET NULL). History preserved.
   */
  contact_id: string | null;
  conversation_id?: string;
  assigned_to?: string;
  title: string;
  value: number;
  currency?: string;
  notes?: string;
  expected_close_date?: string;
  status?: DealStatus;
  created_at: string;
  updated_at?: string;
  contact?: Contact;
  stage?: PipelineStage;
  assignee?: Profile;
}

export type BroadcastStatus = 'draft' | 'scheduled' | 'sending' | 'sent' | 'failed';
export type RecipientStatus = 'pending' | 'sent' | 'delivered' | 'read' | 'replied' | 'failed';

export interface Broadcast {
  id: string;
  user_id: string;
  name: string;
  template_name: string;
  template_language: string;
  template_variables?: Record<string, unknown>;
  audience_filter?: Record<string, unknown>;
  scheduled_at?: string;
  status: BroadcastStatus;
  total_recipients: number;
  sent_count: number;
  delivered_count: number;
  read_count: number;
  replied_count: number;
  failed_count: number;
  /**
   * Set while a server-side delivery pass is fanning out, NULL when
   * idle. Claimed with a conditional UPDATE so two resumes can't both
   * send. Added in migration 038.
   */
  delivery_locked_at?: string | null;
  created_at: string;
}

export interface BroadcastRecipient {
  id: string;
  broadcast_id: string;
  /**
   * Nullable after migration 004 — becomes NULL when the referenced
   * contact is deleted (ON DELETE SET NULL). History preserved; the
   * UI renders "Unknown" for orphaned rows.
   */
  contact_id: string | null;
  status: RecipientStatus;
  sent_at?: string;
  delivered_at?: string;
  read_at?: string;
  replied_at?: string;
  error_message?: string;
  /**
   * Meta's message id, persisted when the broadcast send succeeds so
   * the webhook can mirror status updates back onto the recipient row.
   * Added in migration 003.
   */
  whatsapp_message_id?: string;
  /**
   * Positional body values for this recipient's template send
   * ({{1}}, {{2}}, …), frozen when the broadcast was planned so a
   * server-side resume reproduces the original pass exactly.
   * Added in migration 038; null on rows created before it.
   */
  template_params?: string[] | null;
  created_at: string;
  contact?: Contact;
}

// ============================================================
// Teams (migration 043)
// ============================================================

export interface Team {
  id: string;
  account_id: string;
  name: string;
  description?: string | null;
  color: string;
  created_at: string;
  updated_at: string;
  /** Populated by the list endpoint; absent on bare inserts/updates. */
  members?: TeamMember[];
  /** Open conversations assigned to the team; list endpoint only. */
  open_conversations?: number;
}

export interface TeamMember {
  id: string;
  team_id: string;
  user_id: string;
  added_at: string;
  last_assigned_at?: string | null;
  /** Populated by the list endpoint via a profiles join. */
  full_name?: string;
  email?: string | null;
  avatar_url?: string | null;
}

// ============================================================
// Inbox Views (migration 051)
// ============================================================

/** Schemaless on purpose (stored as JSONB) — mirrors ConversationList's
 *  own filter state so a new filter there never needs a migration here. */
export interface InboxViewFilterConfig {
  filter?: string;
  tagIds?: string[];
  company?: string | null;
  teamId?: string | null;
  labelIds?: string[];
  /** @deprecated single-channel form, kept only so pre-existing saved
   *  views still apply correctly — new saves always write `channelTypes`. */
  channelType?: ChannelType | null;
  /** Multi-select — lets a saved view group channels (e.g. "Email" =
   *  email+gmail, "Everything else" = every non-email channel), not
   *  just isolate one. Empty/absent = no filter. */
  channelTypes?: ChannelType[];
  priority?: ConversationPriority | null;
  sortMode?: string;
}

export interface InboxView {
  id: string;
  account_id: string;
  /** NULL = shared with the whole account; otherwise personal to this user. */
  owner_id: string | null;
  name: string;
  filter_config: InboxViewFilterConfig;
  created_at: string;
  updated_at: string;
}

// ============================================================
// Automations (migration 006)
// ============================================================

export type AutomationTriggerType =
  | 'new_message_received'
  | 'first_inbound_message'
  | 'keyword_match'
  | 'new_contact_created'
  | 'conversation_assigned'
  | 'tag_added'
  | 'conversation_label_added'
  | 'time_based'
  /** Customer tapped a reply button / list row whose id matches; lets
   *  multi-step menus be chained across automations. */
  | 'interactive_reply'
  /** A conversation was closed (by an agent, in bulk, or by an automation).
   *  Dispatched from one server-side place: `closeConversation`. */
  | 'conversation_closed';

export type AutomationStepType =
  | 'send_message'
  | 'send_buttons'
  | 'send_list'
  | 'send_template'
  | 'add_tag'
  | 'remove_tag'
  | 'add_conversation_label'
  | 'remove_conversation_label'
  | 'assign_conversation'
  | 'assign_to_team'
  | 'update_contact_field'
  | 'create_deal'
  | 'wait'
  | 'condition'
  | 'send_webhook'
  | 'close_conversation'
  | 'set_priority'
  | 'set_lifecycle_stage'
  // AI steps (docs/automation-ai.md). "Ask AI (yes/no)" is not a step of its
  // own: it is the `ai_question` subject of a `condition`.
  | 'ai_reply'
  | 'ai_extract'
  | 'ai_summarize'
  | 'ai_translate'
  | 'create_ticket';

export type AutomationLogStatus = 'success' | 'partial' | 'failed';

export interface KeywordMatchTriggerConfig {
  keywords: string[];
  /**
   * `contains` (the default) is a raw substring test, so a short keyword
   * matches inside longer words — "k" fires on "thanks". `word` is the
   * boundary-aware alternative added for issue #409; see
   * `matchesWholeWord` in `@/lib/automations/engine` for its exact
   * semantics. Flows carry their own keyword config and stay
   * substring-only (`@/lib/flows/types`).
   */
  match_type: 'exact' | 'contains' | 'word';
  case_sensitive?: boolean;
}

export interface TagTriggerConfig {
  tag_id: string;
}

/** Same shape as TagTriggerConfig — kept as a distinct alias since it
 *  scopes a different trigger (conversation_label_added, not tag_added). */
export type ConversationLabelTriggerConfig = TagTriggerConfig;

export interface TimeBasedTriggerConfig {
  /** Cron expression or simple HH:mm string; engine can accept either. */
  schedule: string;
  timezone?: string;
}

export interface InteractiveReplyTriggerConfig {
  /** Button / list-row ids to match, exact. Any one matching fires. */
  reply_ids: string[];
}

export type AutomationTriggerConfig =
  | Record<string, never>
  | KeywordMatchTriggerConfig
  | TagTriggerConfig
  | TimeBasedTriggerConfig
  | InteractiveReplyTriggerConfig
  | Record<string, unknown>;

export interface SendMessageStepConfig {
  text: string;
}

/**
 * `send_buttons` / `send_list` step configs carry the full interactive
 * payload (same shape stored on messages + quick replies). `kind` is
 * implied by the step_type but kept on the payload for a uniform shape.
 */
export type SendButtonsStepConfig = InteractiveMessagePayload;
export type SendListStepConfig = InteractiveMessagePayload;

export interface SendTemplateStepConfig {
  template_name: string;
  language?: string;
  variables?: Record<string, string>;
}

export interface TagStepConfig {
  tag_id: string;
}

export interface AssignConversationStepConfig {
  /** 'least_loaded' claims the agent+ profile with the fewest currently
   *  open conversations (`pick_least_loaded_agent`) — the same shape as
   *  'round_robin' but load-aware instead of rotation-based. */
  mode: 'specific' | 'round_robin' | 'least_loaded';
  agent_id?: string;
  /** Skip agents who aren't currently online (migration 053) — 'away'
   *  and 'offline' are both excluded, not just 'offline', since the
   *  point is "won't see this conversation soon". Ignored when
   *  mode is 'specific'. Defaults to false. */
  online_only?: boolean;
}

export interface AssignToTeamStepConfig {
  team_id: string;
  /** 'specific' pins to `agent_id` (validated to be a team member at
   *  run time); 'round_robin' claims the team's next-up member via
   *  `pick_team_round_robin_member`; 'least_loaded' claims the team
   *  member with the fewest open conversations via
   *  `pick_least_loaded_team_member`. */
  mode: 'specific' | 'round_robin' | 'least_loaded';
  agent_id?: string;
  /** Same online-only gate as AssignConversationStepConfig, scoped to
   *  the team's own members. Ignored when mode is 'specific'. */
  online_only?: boolean;
}

export interface UpdateContactFieldStepConfig {
  /**
   * Either a built-in contact column (`name` | `email` | `company`) or a
   * custom field encoded as `custom:<custom_field_id>`. The `custom:` prefix
   * is how the engine distinguishes a `contact_custom_values` write from a
   * direct `contacts` column update. Older configs store the bare column name,
   * so this stays backward compatible.
   */
  field: string;
  /** Supports `{{ vars.* }}` / `{{ message.text }}` interpolation at runtime. */
  value: string;
}

export interface CreateDealStepConfig {
  pipeline_id: string;
  stage_id: string;
  title: string;
  value?: number;
}

export interface WaitStepConfig {
  amount: number;
  unit: 'minutes' | 'hours' | 'days';
}

export type ConditionSubject =
  | 'contact_field'
  | 'tag_presence'
  | 'message_content'
  | 'time_of_day'
  /** Ask AI (yes/no): the operand is a plain-language question about the
   *  conversation. `unsure` and any failure go to the "No" branch. */
  | 'ai_question';

export interface ConditionStepConfig {
  subject: ConditionSubject;
  /** e.g. field name, tag id, substring, or "HH:mm-HH:mm" depending on subject.
   *  For `ai_question`: the question. */
  operand?: string;
  /** For contact_field equals / message_content contains — comparison value */
  value?: string;
  /** `ai_question`: how many of the latest messages the model reads (1 to 30, default 10). */
  ai_messages?: number;
  /** `ai_question`: what a failure does. `no` (default) takes the "No" branch. */
  on_failure?: 'no' | 'stop';
}

/** What an AI step does when the model call fails (or the budget is used up). */
export type AiOnFailure = 'stop' | 'skip' | 'fallback';

export interface AiReplyStepConfig {
  /** `send` (default) sends it to the customer; `draft` leaves an internal note. */
  mode?: 'send' | 'draft';
  /** Extra instructions: tone, what not to promise. Supports variables. */
  instructions?: string;
  /** `match` (default) answers in the customer's language; otherwise a language code. */
  language?: string;
  /** Answer even when a human agent is assigned to the conversation. */
  even_if_assigned?: boolean;
  on_failure?: AiOnFailure;
  /** Sent instead when the AI fails and `on_failure` is `fallback`. */
  fallback_text?: string;
  /** Variable that receives the text of the answer (default `ai_reply`). */
  save_to?: string;
}

export type AiFieldType = 'text' | 'number' | 'date' | 'boolean' | 'choice';

export type AiFieldTarget =
  | { kind: 'contact_field'; field: 'name' | 'email' | 'company' }
  | { kind: 'custom_field'; custom_field_id: string }
  | { kind: 'label' }
  | { kind: 'tag' };

export interface AiExtractField {
  /** Becomes `vars.<key>`. Lower-case letters, digits and underscores. */
  key: string;
  description: string;
  type: AiFieldType;
  /** For `choice`: up to 12 allowed values. */
  choices?: string[];
  /** Optional extra place to save the value, besides `vars.<key>`. */
  target?: AiFieldTarget | null;
}

export interface AiExtractStepConfig {
  fields: AiExtractField[];
  /** Which preset the fields started from (the builder only). */
  preset?: 'sentiment' | 'topic' | null;
  /** Let extracted values replace a contact field that already has one. */
  overwrite?: boolean;
  instructions?: string;
  /** How many of the latest messages the model reads (1 to 30, default 10). */
  ai_messages?: number;
  on_failure?: AiOnFailure;
}

export interface AiSummarizeStepConfig {
  /** Variable that receives the summary (default `summary`). */
  save_to?: string;
  /** Also leave the summary as an internal note on the conversation. */
  post_note?: boolean;
  /** Language code; empty = the workspace language. */
  language?: string;
  on_failure?: AiOnFailure;
}

export interface AiTranslateStepConfig {
  /** Text to translate; empty = the customer's last message. Supports variables. */
  source?: string;
  /** Target language code (e.g. `en`, `ko`, `ms`). */
  target_language: string;
  /** Variable that receives the translation (default `translation`). */
  save_to?: string;
  on_failure?: AiOnFailure;
}

export interface CreateTicketStepConfig {
  category?: TicketCategory;
  priority?: TicketPriority;
  assigned_agent_id?: string | null;
  assigned_team_id?: string | null;
  /** Supports variables. */
  subject: string;
  /** Supports variables. */
  description?: string;
  /** Let the AI write the subject and description from the conversation. */
  ai_write?: boolean;
  /** Do nothing if this conversation already has an open ticket (default true). */
  skip_if_open?: boolean;
}

export interface SendWebhookStepConfig {
  url: string;
  headers?: Record<string, string>;
  body_template?: string;
}

export interface SetPriorityStepConfig {
  priority: ConversationPriority;
}

export interface SetLifecycleStageStepConfig {
  stage: LifecycleStage;
}

export type AutomationStepConfig =
  | SendMessageStepConfig
  | SendButtonsStepConfig
  | SendListStepConfig
  | SendTemplateStepConfig
  | TagStepConfig
  | AssignConversationStepConfig
  | AssignToTeamStepConfig
  | SetPriorityStepConfig
  | SetLifecycleStageStepConfig
  | UpdateContactFieldStepConfig
  | CreateDealStepConfig
  | WaitStepConfig
  | ConditionStepConfig
  | SendWebhookStepConfig
  | AiReplyStepConfig
  | AiExtractStepConfig
  | AiSummarizeStepConfig
  | AiTranslateStepConfig
  | CreateTicketStepConfig
  | Record<string, never>
  | Record<string, unknown>;

export interface Automation {
  id: string;
  /** Account tenancy key — every automation belongs to one account
   *  (migration 017 made the column NOT NULL). The engine looks up
   *  active automations by this field on inbound webhook events. */
  account_id: string;
  /** Original author. Used for log audit + outbound message
   *  sender-of-record, never for tenancy isolation. */
  user_id: string;
  name: string;
  description?: string;
  trigger_type: AutomationTriggerType;
  trigger_config: AutomationTriggerConfig;
  is_active: boolean;
  execution_count: number;
  last_executed_at?: string | null;
  created_at: string;
  updated_at: string;
}

export interface AutomationStep {
  id: string;
  automation_id: string;
  parent_step_id?: string | null;
  branch?: 'yes' | 'no' | null;
  step_type: AutomationStepType;
  step_config: AutomationStepConfig;
  position: number;
  created_at: string;
}

export interface AutomationLogStepResult {
  step_id: string;
  step_type: AutomationStepType;
  status: 'success' | 'skipped' | 'failed';
  detail?: string;
  /** AI steps: what the step decided (`answered`, `yes`, `extracted`, `failed` ...). */
  outcome?: string;
  /** AI steps: tokens the call used. */
  tokens?: number;
  /** AI steps: the model output, cut to 500 characters. Never the prompt. */
  output?: string;
}

export interface AutomationLog {
  id: string;
  automation_id: string;
  user_id: string;
  contact_id: string | null;
  trigger_event: string;
  steps_executed: AutomationLogStepResult[];
  status: AutomationLogStatus;
  error_message?: string | null;
  created_at: string;
  contact?: Contact;
}

// ============================================================
// Quick replies — reusable snippets (migration 035)
// ============================================================

export type QuickReplyKind = 'text' | 'interactive';

export interface QuickReply {
  id: string;
  /** Account tenancy key — shared across all members of the account. */
  account_id: string;
  /** Author / audit only. */
  user_id: string;
  title: string;
  kind: QuickReplyKind;
  /** Set when `kind === 'text'`. */
  content_text?: string | null;
  /** Set when `kind === 'interactive'`. */
  interactive_payload?: InteractiveMessagePayload | null;
  created_at: string;
  updated_at: string;
  /** Propose and approve (migration 084); same meaning as on `Tag`. */
  approval_status?: 'approved' | 'pending' | 'rejected';
  proposed_by?: string | null;
  proposed_at?: string | null;
  decided_by?: string | null;
  decided_at?: string | null;
  decision_note?: string | null;
  pending_edit?: Record<string, unknown> | null;
  edit_status?: 'pending' | 'rejected' | null;
}

// ============================================================
// Sembang — internal team chat (migration 098)
//
// Walled off from the customer-facing Inbox: channels (public/private),
// membership with a moderator role (creator auto-promoted by a DB
// trigger), plain-text messages with @mentions, file attachments in a
// private bucket. See supabase/ci/drafts/098_sembang_p0.sql for the
// underlying tables/RLS/RPCs. The shapes below are the camelCased JSON
// the API routes under src/app/api/sembang/ return.
// ============================================================

export type SembangMemberRole = 'member' | 'moderator';

/** A channel row, as returned by the channel-detail / create routes. */
export interface SembangChannel {
  id: string;
  accountId: string;
  /** Null for a DM (`isDm: true`) — DMs show participant names instead. */
  name: string | null;
  topic: string | null;
  isPrivate: boolean;
  /** Migration 100. A DM is a `sembang_channels` row with `isDm: true` —
   *  same messages/reactions/pins/tasks tables, no parallel schema. */
  isDm: boolean;
  createdBy: string;
  createdAt: string;
  archivedAt?: string | null;
  /** The caller's membership role — null for a public channel they can
   *  see but haven't joined yet. Never null for a DM (fixed membership). */
  memberRole: SembangMemberRole | null;
  /** Migration 101. The CALLER's own mute state for this channel —
   *  personal, not a channel-wide setting. False for a channel the
   *  caller can see but hasn't joined (no membership row to read). */
  muted: boolean;
}

/**
 * One row of `list_sembang_channels_for_current_user` — the sidebar's
 * channel list (GET /api/sembang/channels), already unread-counted.
 */
export interface SembangChannelSummary {
  id: string;
  name: string | null;
  topic: string | null;
  isPrivate: boolean;
  /** Migration 100. See `SembangChannel.isDm`. */
  isDm: boolean;
  createdBy: string;
  createdAt: string;
  memberRole: SembangMemberRole;
  lastReadAt: string;
  unreadCount: number;
  lastMessageBody: string | null;
  lastMessageAt: string | null;
  lastMessageAuthorId: string | null;
  /** Migration 100. Only populated when `isDm` is true — the OTHER
   *  participant(s), for rendering a DM row's display name/avatars
   *  without a second fetch. Null (not empty array) for a real channel. */
  dmParticipantNames: string[] | null;
  dmParticipantAvatarUrls: (string | null)[] | null;
  /** Migration 101. The caller's own mute state — see `SembangChannel.muted`. */
  muted: boolean;
  /** Unread `sembang_mention`/`sembang_dm_message` notifications for this
   *  channel — a subset of `unreadCount` (every unread message counts
   *  toward `unreadCount`, only ones that @mentioned the caller or were a
   *  DM count here too). Task-assignment notifications are excluded —
   *  those already have their own per-channel Tasks affordance. */
  unreadMentionCount: number;
}

/** A file attached to a Sembang message. `url` is a short-lived signed
 *  URL the GET messages route resolves server-side (the bucket is private). */
export interface SembangAttachment {
  id: string;
  messageId: string;
  filename: string;
  sizeBytes: number;
  mimeType: string | null;
  url: string;
  createdAt: string;
}

/** One emoji's aggregated reactions on a message — the shape the
 *  message list/thread routes group `sembang_reactions` rows into. */
export interface SembangReactionSummary {
  emoji: string;
  count: number;
  userIds: string[];
  /** Convenience — `userIds.includes(caller.id)`, precomputed server-side. */
  reactedByMe: boolean;
}

export interface SembangMessage {
  id: string;
  channelId: string;
  accountId: string;
  authorId: string;
  body: string;
  /** Plain array of mentioned user-id strings (not objects). */
  mentions: string[];
  /** Migration 099. Set only on a top-level message that is itself a
   *  thread reply's parent — threads are flat, one level, so a reply's
   *  own `parentMessageId` never points at another reply. */
  parentMessageId: string | null;
  /** Migration 099. Set once the author edits the body. */
  editedAt: string | null;
  deletedAt: string | null;
  deletedBy: string | null;
  createdAt: string;
  /** Joined from `profiles`; null if the author's profile was removed. */
  author: { id: string; fullName: string; avatarUrl: string | null } | null;
  attachments: SembangAttachment[];
  /** Migration 099. Empty array when the message has none. */
  reactions: SembangReactionSummary[];
  /** Migration 100. Personal — whether the CALLER has starred this
   *  message, precomputed server-side (same shape as `reactedByMe`). */
  starredByMe: boolean;
  /**
   * Migration 099. Only populated on TOP-LEVEL messages (parentMessageId
   * null) by the channel message list — a reply row leaves these
   * undefined rather than computing them for something that can't itself
   * have replies (threads are flat).
   */
  replyCount?: number;
  lastReplyAt?: string | null;
  /** Migration 101. Only meaningful when `parentMessageId` is set — a
   *  reply the author chose to also post into the main channel
   *  timeline (Slack's "Also send to #channel"), immutable after
   *  creation. False for a normal thread-only reply. */
  alsoInChannel: boolean;
  /** Migration 101. Populated whenever `parentMessageId` is set, so a
   *  reply rendered in the main timeline (because `alsoInChannel`) can
   *  show "replied to a thread: <snippet>" without a second fetch.
   *  Null for a top-level message; also null if the parent itself was
   *  deleted/not found. */
  parentPreview?: { id: string; body: string; authorName: string } | null;
}

/** A channel member row, joined with `profiles` (GET .../members). */
export interface SembangMember {
  userId: string;
  role: SembangMemberRole;
  joinedAt: string;
  lastReadAt: string;
  fullName: string;
  avatarUrl: string | null;
}

/** Migration 099. One pinned message (GET .../pins), hydrated with the
 *  full message the same way the channel message list is. */
export interface SembangPin {
  channelId: string;
  messageId: string;
  pinnedBy: string;
  pinnedByName: string;
  pinnedAt: string;
  message: SembangMessage;
}

export type SembangTaskStatus = 'open' | 'done';

/** Migration 099. A standalone, per-channel checklist item. Migration 103
 *  adds the one deliberate, write-once link into the Tickets module
 *  (`ticketId`) — see the requirements doc's decision. */
export interface SembangTask {
  id: string;
  channelId: string;
  accountId: string;
  /** The message this task was created from, if any. */
  messageId: string | null;
  title: string;
  assigneeId: string | null;
  assignee: { id: string; fullName: string; avatarUrl: string | null } | null;
  status: SembangTaskStatus;
  dueAt: string | null;
  createdBy: string;
  createdByName: string;
  createdAt: string;
  /** Server-stamped on the actor's own UPDATE — never client-supplied
   *  (see the sembang_tasks_guard() trigger in migration 099). */
  completedAt: string | null;
  completedBy: string | null;
  /** Migration 103 — the one deliberate exception to "no FK into
   *  Tickets": set once a real Ticket has been created from this task,
   *  write-once (see sembang_tasks_guard()). */
  ticketId: string | null;
  /** For display ("View VIR-12") — null until `ticketId` is set. */
  ticketNumber: number | null;
}

// ------------------------------------------------------------
// Sembang P4 — Files, Links, Bookmarks (migration 104)
// ------------------------------------------------------------

/** One attachment, from GET .../channels/[id]/files — every file ever
 *  sent in the channel, most recent first. Same shape as
 *  `SembangAttachment` plus who sent it, since the Files list isn't
 *  scoped to one message the way a rendered message row is. */
export interface SembangFileItem {
  id: string;
  messageId: string;
  filename: string;
  sizeBytes: number;
  mimeType: string | null;
  url: string;
  createdAt: string;
  authorId: string;
  authorName: string;
}

/** One URL found in a channel's messages, from GET .../channels/[id]/links.
 *  No unfurl/preview — just the raw URL plus where it came from. A
 *  message with three links in its body produces three `SembangLinkItem`
 *  rows (one per URL), all sharing the same `messageId`. */
export interface SembangLinkItem {
  url: string;
  messageId: string;
  authorId: string;
  authorName: string;
  createdAt: string;
}

/** Migration 104. A channel-level curated bookmark — distinct from a
 *  personal Star (private, migration 100) and from a Pin (pins a
 *  specific MESSAGE, migration 099). Any member adds one; the adder, a
 *  moderator, or an admin can remove it. */
export interface SembangBookmark {
  id: string;
  channelId: string;
  url: string;
  title: string | null;
  addedBy: string;
  addedByName: string;
  addedAt: string;
}

// ------------------------------------------------------------
// Sembang P2 — direct messages, cross-conversation search, starred
// messages (migration 100)
// ------------------------------------------------------------

/**
 * GET /api/sembang/stars — one row of the caller's personal starred-
 * message list, hydrated with enough channel context to render without
 * a second fetch (the Starred view spans every channel/DM at once).
 */
export interface SembangStarredMessage {
  message: SembangMessage;
  starredAt: string;
  channel: {
    id: string;
    name: string | null;
    isDm: boolean;
    dmParticipantNames: string[] | null;
  };
}

/**
 * GET /api/sembang/search — one row of a cross-channel/DM message
 * search result, same channel-context shape as `SembangStarredMessage`.
 */
export interface SembangSearchResult {
  message: SembangMessage;
  channel: {
    id: string;
    name: string | null;
    isDm: boolean;
    dmParticipantNames: string[] | null;
  };
}

// ------------------------------------------------------------
// Sembang P3 — global threads view, member directory, browse public
// channels, per-channel/DM mute, "also send to #channel" (migration 101)
// ------------------------------------------------------------

/**
 * GET /api/sembang/threads — one row of "every thread you're in"
 * (you started it, replied to it, or were @mentioned in it), across
 * every channel/DM. `message` is always the THREAD-STARTING top-level
 * message (with `replyCount`/`lastReplyAt` populated), same channel-
 * context shape as search/starred.
 */
export interface SembangThreadSummary {
  message: SembangMessage;
  channel: {
    id: string;
    name: string | null;
    isDm: boolean;
    dmParticipantNames: string[] | null;
  };
}

/**
 * GET /api/sembang/directory — one row of everyone in the account who
 * currently holds the `menu.sembang` capability (not just people who
 * happen to share a channel with the caller).
 */
export interface SembangDirectoryMember {
  userId: string;
  fullName: string;
  avatarUrl: string | null;
  accountRole: string;
}

/**
 * GET /api/sembang/channels/browse — a public, non-DM channel the
 * caller can see but hasn't joined yet.
 */
export interface SembangBrowseChannel {
  id: string;
  name: string;
  topic: string | null;
  memberCount: number;
}

/**
 * GET /api/sembang/mentions — one unread `sembang_mention`/
 * `sembang_dm_message` notification, hydrated with the message and
 * channel context (same shape as search/starred/threads). `notificationId`
 * is what the "mark as done" action updates — a direct client-side
 * `notifications.read_at` write, same mechanism the Notifications page
 * already uses.
 */
export interface SembangMentionItem {
  notificationId: string;
  createdAt: string;
  message: SembangMessage | null;
  channel: {
    id: string;
    name: string | null;
    isDm: boolean;
    dmParticipantNames: string[] | null;
  };
}

